### ISSUE TITLE
Clarification needed: [which curl returns different path]

### ISSUE THREAD

**Issue by luisdrg** [comp426-2022-fall/a00#17]
For COMP-421 I am required to install Anaconda with Python, so now when I enter `which curl` on my terminal I get `/Users/luisrivera/opt/anaconda3/bin/curl` instead of `/usr/bin/curl`

Is it okay to leave it like that?

**Comment by jdmar3** [comment]
It shouldn't cause a conflict. It's just curl at a different path. But what version of curl is it? That is really the only thing that might be of concern for you. Like you might want to know if the versions of curl match or not. You can always run a program from its full path, so if you need the system curl installed in /usr/bin instead of the one installed in your user opt directory, you can just run it with /usr/bin/curl.
