### ISSUE TITLE
Clarification needed: The install_check.sh script not present

### ISSUE THREAD

**Issue by AyBruno** [comp426-2022-fall/a00#2]
Under the "Run a script and then push the output back to GitHub" section of assignment 0 the instructions reference a script "install_check.sh" but it doesn't appear to be in the repo.

**Comment by HuGuo-UNC-Chapel-Hill** [comment]
I did not find the file "install_check.sh" in the folder.   

![Screen Shot 2022-08-18 at 9 52 49 AM](https://user-images.githubusercontent.com/86079744/185413183-e3fbb663-a120-412c-8938-f84af3b297de.png)
.

**Comment by jdmar3** [comment]
Indeed that is a huge problem. I seem to have forgotten to add the file entirely. 😖 

It is here now: https://github.com/comp426-2022-fall/a00/blob/main/install_check.sh 

You can just add that file to your repository directly. I am going to try to push an update to everyone's existing repositories. New repos beyond this point will have the file when they are created.

**Comment by jdmar3** [comment]
The repo update link is apparently not working, so for now, disregard this comment and just get the file from the template repository, linked in the above comment.

~~Alright, so the fix is simpler than me creating pull requests to all repos.~~

~~Everyone who currently does not have the `install_check.sh` file should be able to go to the assignment invite link again (included below) and then click on the "update" link that appears just below the repo page address. See image below.~~

![updaterepo](https://user-images.githubusercontent.com/2459227/185481632-fd445eba-08db-4e4e-81c1-4d3eaf91df86.png)

~~a00 invite link:~~ 
~~https://classroom.github.com/a/TLIqqWVj~~

**Comment by Lesram21** [comment]
I click on the "update" link under the repo address but nothing seems to happen. I go into my repository and the file is still not there.

**Comment by jdmar3** [comment]
Hrmm. It took a while for it to update when I did this with my test repo. and I'm not sure what is going on. The even easier fix is to just grab the file from the template repository and add it to your local repo, run it, and then push it, like in the assignment. 

I mentioned this in my comment above: 

"It is here now: https://github.com/comp426-2022-fall/a00/blob/main/install_check.sh

"You can just add that file to your repository directly. I am going to try to push an update to everyone's existing repositories. New repos beyond this point will have the file when they are created."
