### ISSUE TITLE
Changing a UNIX username

### ISSUE THREAD

**Issue by mayather** [comp426-2022-fall/a00#8]
#### URL of file with confusing thing
https://www.cyberciti.biz/faq/howto-change-rename-user-name-id/

#### Line number of confusing thing
Linux Change or Rename User Command Syntax

#### What is confusing?
When I first downloaded Ubuntu, I accidentally closed the window where you create your UNIX login info. I was able to figure out how to change my password, but when I try using the usermod command to change my username, it says "usermod: user root is currently used by process 1." How do I fix this?

**Comment by jdmar3** [comment]
The easiest thing to do when you break something in an install like this (and this goes with installing Linux directly on hardware as well), is to just start over. You're not losing anything, because you don't have a working environment that you are worried about protecting.

So, rather than forging ahead, blow away the WSL install and start a new one. This link is a guide to completely removing a Linux distro from WSL: https://www.windowscentral.com/how-completely-remove-linux-distro-wsl

Once you do that, then you can start again and not close the window mid install this time.

**Comment by mayather** [comment]
After removing and redownloading the WSL and creating my UNIX user id and password, the NVM and Node downloads I had done before aren't working anymore. When I type "command -v nvm" into the command prompt, I get the message "'command' is not recognized as an internal or external command, operable program or batch file." Since the nvm command doesn't work, I can't confirm node is still properly downloaded. How do I fix this?

**Comment by jdmar3** [comment]
See #7.
